### ISSUE TITLE
Legio Krytos

### ISSUE THREAD

**Issue by zopha** [BSData/adeptus-titanicus#158]
Adding changes for Legio Krytos from the Traitors book.

Maniple Changes
- [ ] Axiom maniple
- [ ] Myrmidon maniple
- [ ] Regia maniple
- [ ] Precept maniple
- [ ] Fortis maniple

Legio Wargear
- [x] Earthshaker points change
- [ ] Earthshake Profile

Legio Traits
- [x] Doom of Worlds (text for maniple changes)

Princep Traits
- [x] Godlike Contempt
- [x] World Bane
- [x] Path of Iron

Legio Strat
~~- [ ] Destroyers of Cities~~
~~- [ ] Civilisation’s Ruin~~

**Comment by zopha** [comment]
Maniple Changes
- [ ] Axiom maniple
- [ ] Myrmidon maniple
- [ ] Regia maniple
- [ ] Precept maniple
- [ ] Fortis maniple

Legio Wargear
- [ ] Earthshaker points change
- [ ] Earthshake Profile

Legio Traits
- [ ] Masters of Flame
- [ ] Dark Blessing

Princep Traits
- [ ] Butcher
- [ ] World Burner
- [ ] Methodical

Legio Strat
- [ ] Burned Ones

**Comment by zopha** [comment]
I have two hidden profiles for the earthshaker missiles in place, it's slightly different for a reaver and warlord, but haven't found an easy way to unhide them. I'll come back to it later or if anyone else can take a look at it.

Maniple changes for Krytos still need to be done as well.

**Comment by zopha** [comment]
I'm not quite sure why it's like that either, it seems to be coming through because of the modifier conditions on the profile. At least that seems the most likely source but just too tired at the moment to figure it out.

The maniple changes look good although I think we'll need to find another way of doing replacement titans otherwise it may become an issue futher down the line. The cat file gets larger and everything gets loaded so slows down with more entries even if they aren't used. I'm not sure what to do with them tbh.

**Comment by MoDLegion** [comment]
I found a lot cleaner way of doing the model replacement. If we use a selection entry that just selects a 'x replaces y' category, you can then just modify the min/max selections accordingly and looks like this in the editor:
![image](https://user-images.githubusercontent.com/97483529/149639265-06705d25-10a7-47a1-9afb-40b85c2c9628.png)

This eliminates the need for duplicating each titan entry for each Legio, is reusable across Legios (they can just all use the same category, as you can't have 2 Legios in a Maniple). The only downside I can see is that you get a 'Replace X with Y' category and selection entry in your Maniple when you print the roster, which looks like this:
![image](https://user-images.githubusercontent.com/97483529/149639279-9f80c71e-36af-4afc-bfb1-4a861bdf987c.png)

I think that's a minor issue in relation to the mess that having to update every single copied titan entry can become. I'll have to double check it works correctly for Maniples that can be affect by multiple Legios (like Fortis) but I don't think it's an issue. Even if 2 Legios would actually affect a single Maniple (which you can currently do due to #209) I'm just in/decrementing the min max so while the number might not ne legal it wouldn't actually catastrophically break.
