### ISSUE TITLE
Canis Light Maniple

### ISSUE THREAD

**Issue by twizted86** [BSData/adeptus-titanicus#202]
The Canis Light Maniple isn't showing up under Maniples

**Comment by MoDLegion** [comment]
It is actually in the data, but it is a Legio specific Maniple, but for some reason the entry has been hidden back in #108. My assumption would be by mistake because because in the related commit a whole bunch of Legio specific items where set to hidden by default, including this one. It doesn't make sense for for a Maniple entry though because there is no way to make it visible again, obviously.
