### ISSUE TITLE
Corrupted  Titan Personal Traits missing

### ISSUE THREAD

**Issue by GMTemplar** [BSData/adeptus-titanicus#246]
As per Traitor Legios book, corrupted Princeps Seniores should not have access to the general personal traits table at all. Instead they should only have access to Corrupted Titan Personal Traits and Legio Specific Personal Traits.

**Comment by MoDLegion** [comment]
Sigh this is one of those 'impossible' to fix issues. Because 'Corrupted Titan' is a selection on a titan, the 'Personal Trait' selection group on a 'Princeps Seniores' selection is not able to see whether or not 'Corrupted Titan' is selected (because it's not in a Parent selection, but an ancestor). The only way to fix this is moving a the personal traits into each titan so the proper conditions can be made. Not a 100% ideal solution but I think it works for now.
