### ISSUE TITLE
Favourite titans taken into maniples

### ISSUE THREAD

**Issue by Dread-AT18** [BSData/adeptus-titanicus#43]
Can there be an option to add favourite titans to maniple's? You click the + and have the relevant favourite titan available in the associated Maniple slot? Or have a favourites slot on the maniple's list?

**Comment by bjUndergound** [comment]
I will certainly look into the feasibility of this kind of feature, though it may require a significant change to accomplish so might be a little time til I have a solution for you. 

I think it might be possible BUT you will almost certainly need to be more judicious in terms of what you choose to add because as far as I am aware it will not be a trivial task to determine which of your favourites should be displayed. 

Leave it with me and check back here for messages in the future

**Comment by bjUndergound** [comment]
Having had a look at this, if it is possible, I don't think it'll be possible to implement in this module. There are no apparent mechanisms to access client/local items I'm afraid. Favourites is a pro feature so is possibly less supported at the software level than you might think.

I will keep looking, but i wouldn't expect this to be implemented soon

**Comment by Dread-AT18** [comment]
Thanks for checking.  It just seems that make sense for AT18. Maje you favourite titans in a list then pop them into maniples as you need them. Saves a lot of typing etc.  Keep up the good work.




Get Outlook for Android







On Wed, Mar 4, 2020 at 1:46 AM +0000, "BJ-Gee" <notifications@github.com> wrote:












Having had a look at this, if it is possible, I don't think it'll be possible to implement in this module. There are no apparent mechanisms to access client/local items I'm afraid. Favourites is a pro feature so is possibly less supported at the software level than you might think.


I will keep looking, but i wouldn't expect this to be implemented soon

**Comment by capitaladot** [comment]
Yeah, sadly, this is a bad BattleScribe design decision and would take action from @Jonskichov in a new version to implement.
